//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Showroom.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoffeeFacts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoffeeFacts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Showroom.Resources.CoffeeFacts", typeof(CoffeeFacts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabica coffee is believed to have been introduced to the Cordillera highlands in the mid-19th century. According to William F. Pack, an American governor of Benguet (1909-1912) during the American colonial period, arabica coffee was first introduced to the Cordilleras in 1875 by a Spanish military governor of Benguet, Manuel Scheidnegal y Sera. He initially planted them in government gardens in the lowlands of the province to evaluate their potential as a regional crop. However, frequent rains and the low  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Benguet {
            get {
                return ResourceManager.GetString("Benguet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bourbon is the most famous of the Bourbon-descended varieties (see History of Bourbon and Typica for a full history of this group of coffees). It is a tall variety characterized by relatively low production, susceptibility to the major diseases, and excellent cup quality.
        ///
        ///French missionaries introduced Bourbon from Yemen to Bourbon Island (now La Réunion)—giving it the name it has today—in the early 1700s. Until the mid-19th century, Bourbon did not leave the island. But beginning in the mid-1800s, the v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Bourbon {
            get {
                return ResourceManager.GetString("Bourbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cross between highly productive Mundo Novo and compact Caturra, made by the Instituto Agronomico (IAC) of Sao Paulo State in Campinas, Brazil. The plant is highly productive compared to Bourbon, in part because of its small size, which allows plants to be closely spaced; it can be planted at nearly double the density. The plant’s shape makes it relatively easy apply pest and disease treatments. It is mainly characterized by great vigor and its low height; it is less compact than Caturra. It is highly susc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Catuai {
            get {
                return ResourceManager.GetString("Catuai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caturra is a natural mutation of the Bourbon variety. It was discovered on a plantation in the state of Minas Gerais in Brazil sometime between 1915 and 1918.
        ///
        ///Caturra has a single-gene mutation that causes the plant to grow smaller (called dwarfism). Its name derives from the Guarani word meaning &quot;small.&quot; It is also called &quot;Nanico.&quot; After Caturra’s discovery, selections were made by the Instituto Agronomico (IAC) of Sao Paulo State in Campinas, Brazil, starting in 1937. Breeders were interested in Caturr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Caturra {
            get {
                return ResourceManager.GetString("Caturra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charrier coffee, (Coffea charrieriana), species of coffee plant (genus Coffea, family Rubiaceae) found in Central Africa that was the first discovered to produce caffeine-free beans (seeds). Endemic to the Bakossi Forest Reserve in western Cameroon, the plant inhabits steep rocky slopes of wet rainforests. Charrier coffee was first collected in 1983; however, it was first described scientifically in 2008 after a morphological study discovered that it did not conform to descriptions of known Coffea species.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Charrier {
            get {
                return ResourceManager.GetString("Charrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This variety was originally collected from coffee forests in Ethiopia in the 1930s. From there, it was sent to the Lyamungu research station in Tanzania, and then brought to Centro Agronómico Tropical de Investigación y Enseñanza (CATIE) in Central America in the 1953, where it was logged as accession T2722. It was distributed throughout Panama via CATIE in the 1960s after it had been recognized for tolerance to coffee leaf rust. However, the plant&apos;s branches were brittle and not favored by farmers so it wa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Geisha {
            get {
                return ResourceManager.GetString("Geisha", resourceCulture);
            }
        }
    }
}
